// swift-tools-version: 6.0
// OpenWisper — system-wide local-first AI dictation for macOS.
//
// Target layout is deliberate: each Wave-A task owns exactly one library target
// (see docs/TASKS.md) so parallel workers never touch the same files. Only Task W1
// may edit this manifest, and only the CWhisper / WhisperLocal / whisper-smoke entries.
import PackageDescription

let package = Package(
    name: "OpenWisper",
    platforms: [.macOS(.v14)],
    targets: [
        // Contracts, config, env, permissions, logging, fakes. FROZEN during Wave A.
        .target(
            name: "OpenWisperCore",
            path: "Sources/OpenWisperCore"
        ),

        // C bindings to whisper.cpp (Task W1). The headers under
        // Sources/CWhisper/include are copies regenerated by
        // scripts/fetch_whisper.sh (`make deps`) — see Sources/CWhisper/include/CWhisper.h.
        .target(
            name: "CWhisper",
            path: "Sources/CWhisper"
        ),

        // Local whisper.cpp engine (Task W1). Links the merged static archive
        // produced by `make deps`; paths are relative to the package root, which
        // is where all builds are invoked from.
        // The framework list is what `nm -u` on libwhisper_merged.a actually
        // leaves unresolved — no more (MetalKit, for instance, is not needed):
        //   Accelerate — cblas_sgemm + vDSP_* from ggml-blas / ggml-cpu
        //   Metal      — MTLCreateSystemDefaultDevice etc. from ggml-metal, built
        //                with GGML_METAL_EMBED_LIBRARY so the shader source ships
        //                inside the archive and is compiled at runtime (this host
        //                has no Metal toolchain)
        //   Foundation — NSString/NSURL/NSLock from ggml-metal's ObjC sources
        //   -lc++      — whisper.cpp and ggml are C++
        .target(
            name: "WhisperLocal",
            dependencies: ["OpenWisperCore", "CWhisper"],
            path: "Sources/WhisperLocal",
            linkerSettings: [
                .unsafeFlags(["-LVendor/whisper-install/lib", "-lwhisper_merged", "-lc++"]),
                .linkedFramework("Accelerate"),
                .linkedFramework("Metal"),
                .linkedFramework("Foundation"),
            ]
        ),

        // Cloud STT (Groq/OpenAI Whisper API) + LLM transcript cleanup (Task W3).
        .target(
            name: "CloudAI",
            dependencies: ["OpenWisperCore"],
            path: "Sources/CloudAI"
        ),

        // Text insertion: pasteboard + Cmd-V / synthetic typing (Task W3).
        .target(
            name: "InsertIO",
            dependencies: ["OpenWisperCore"],
            path: "Sources/InsertIO"
        ),

        // Floating recording pill overlay (Task W4).
        .target(
            name: "PillUI",
            dependencies: ["OpenWisperCore"],
            path: "Sources/PillUI"
        ),

        // Menu bar item, engine switcher, launch-at-login (Task W5).
        .target(
            name: "MenuBarUI",
            dependencies: ["OpenWisperCore"],
            path: "Sources/MenuBarUI"
        ),

        // The app window — History / Model / Permissions (Wave D). Like
        // MenuBarUI it talks to the running app only through injected closures
        // (`MainWindowActions`), so it builds and renders on its own.
        .target(
            name: "MainWindowUI",
            dependencies: ["OpenWisperCore"],
            path: "Sources/MainWindowUI",
            // The brand image (Theme.swift resolves the bundle by hand so a
            // mis-assembled app degrades to the app icon instead of trapping
            // in Bundle.module; make_app.sh copies *.bundle into the .app).
            resources: [.copy("Resources/monkey-512.jpg")]
        ),

        // Hotkey event tap, mic recorder, dictation state machine (Task W2).
        .target(
            name: "Spine",
            dependencies: ["OpenWisperCore"],
            path: "Sources/Spine"
        ),

        // The app executable — wired during Wave B integration.
        .executableTarget(
            name: "OpenWisper",
            dependencies: [
                "OpenWisperCore", "WhisperLocal", "CloudAI",
                "InsertIO", "PillUI", "MenuBarUI", "MainWindowUI", "Spine",
            ],
            path: "Sources/OpenWisperApp"
        ),

        // Standalone verification executables (safe to build/run in isolation).
        .executableTarget(
            name: "whisper-smoke",
            dependencies: ["OpenWisperCore", "WhisperLocal"],
            path: "Sources/whisper-smoke"
        ),
        .executableTarget(
            name: "pill-demo",
            dependencies: ["OpenWisperCore", "PillUI"],
            path: "Sources/pill-demo"
        ),
        // Offscreen snapshots of the three window pages. Deliberately does NOT
        // depend on WhisperLocal: it must run without a model, without Metal,
        // and without the ggml exit-abort hazard that comes with them.
        .executableTarget(
            name: "window-demo",
            dependencies: ["OpenWisperCore", "MainWindowUI"],
            path: "Sources/window-demo"
        ),

        .testTarget(
            name: "UnitTests",
            dependencies: ["OpenWisperCore", "CloudAI", "InsertIO", "Spine"],
            path: "Tests/UnitTests"
        ),
    ],
    // Swift 5 language mode: pragmatic concurrency checking for AppKit-heavy code.
    swiftLanguageVersions: [.v5]
)
