// CWhisper — umbrella header exposing the whisper.cpp C API to Swift.
//
// The whisper.h / ggml*.h files sitting next to this one are COPIES generated by
// scripts/fetch_whisper.sh (`make deps`) from the pinned whisper.cpp tag. Do not
// hand-edit them — edit the script and re-run it. They are checked in (rather
// than pointed at Vendor/) because SwiftPM needs a stable public headers
// directory that exists before whisper.cpp has been vendored.
//
// The script copies exactly the transitive closure of whisper.h's quoted
// includes, so including whisper.h here covers every header in this directory
// and keeps the SwiftPM-generated module map's umbrella complete.
//
// The actual object code lives in Vendor/whisper-install/lib/libwhisper_merged.a
// and is linked in by the WhisperLocal target (see Package.swift).
#ifndef OPENWISPER_CWHISPER_H
#define OPENWISPER_CWHISPER_H

#include "whisper.h"

#endif /* OPENWISPER_CWHISPER_H */
